# backup.tst

    >>> from Test.backup import run
    >>> run.run()
    Traceback (most recent call last):
        ...
    KeyError: '$ans not bound'

